server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: exchange

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:exchange;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
    defer-datasource-initialization: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

external:
  api:
    base-url: "https://open.er-api.com/v6/latest"

app:
  jwtSecret: c9880eb4e4efec654e6fcabcebd9dde5db150ade62c2aadd547e5a5dad2064bc
  jwtExpirationMs: 86400000